name: release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - id: get-version
        uses: battila7/get-version-action@v2

      - uses: actions/checkout@v2
        with:
          submodules: true

      - id: release-asset
        run: |
          version=${{ steps.get-version.outputs.version-without-v }}
          cd ..
          cp -r libuhttpd libuhttpd-$version
          rm -rf libuhttpd-$version/.git*
          rm -rf libuhttpd-$version/src/http-parser/.git*
          rm -rf libuhttpd-$version/src/buffer/.git*
          rm -rf libuhttpd-$version/src/ssl/.git*
          rm -rf libuhttpd-$version/src/log/.git*
          tar zcfv libuhttpd-$version.tar.gz libuhttpd-$version

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          files: ../libuhttpd-*.tar.gz